//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LndrMeApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LndrMeApp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about {0} hours.
        /// </summary>
        internal static string AboutMultipleHours {
            get {
                return ResourceManager.GetString("AboutMultipleHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about 1 hour.
        /// </summary>
        internal static string AboutOneHour {
            get {
                return ResourceManager.GetString("AboutOneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about 1 month.
        /// </summary>
        internal static string AboutOneMonth {
            get {
                return ResourceManager.GetString("AboutOneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about 1 year.
        /// </summary>
        internal static string AboutOneYear {
            get {
                return ResourceManager.GetString("AboutOneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to available.
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test@example.com.
        /// </summary>
        internal static string DefaultEMail {
            get {
                return ResourceManager.GetString("DefaultEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half a minute.
        /// </summary>
        internal static string HalfAMinute {
            get {
                return ResourceManager.GetString("HalfAMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than a minute.
        /// </summary>
        internal static string LessThanAMinute {
            get {
                return ResourceManager.GetString("LessThanAMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than 5 seconds.
        /// </summary>
        internal static string LessThanFiveSeconds {
            get {
                return ResourceManager.GetString("LessThanFiveSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than 10 seconds.
        /// </summary>
        internal static string LessThanTenSeconds {
            get {
                return ResourceManager.GetString("LessThanTenSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than 20 seconds.
        /// </summary>
        internal static string LessThanTwentySeconds {
            get {
                return ResourceManager.GetString("LessThanTwentySeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about {0} days.
        /// </summary>
        internal static string MultipleDays {
            get {
                return ResourceManager.GetString("MultipleDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        internal static string MultipleMinutes {
            get {
                return ResourceManager.GetString("MultipleMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months.
        /// </summary>
        internal static string MultipleMonths {
            get {
                return ResourceManager.GetString("MultipleMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to over {0} years.
        /// </summary>
        internal static string MultipleYears {
            get {
                return ResourceManager.GetString("MultipleYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day.
        /// </summary>
        internal static string OneDay {
            get {
                return ResourceManager.GetString("OneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute.
        /// </summary>
        internal static string OneMinute {
            get {
                return ResourceManager.GetString("OneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://lndr.me/.
        /// </summary>
        internal static string ServerBaseURI {
            get {
                return ResourceManager.GetString("ServerBaseURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y9dghu2e9hdgw9g2iowdghh89982gijb.
        /// </summary>
        internal static string ServerKey {
            get {
                return ResourceManager.GetString("ServerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to receive.json.
        /// </summary>
        internal static string ServerReceiveEndpoint {
            get {
                return ResourceManager.GetString("ServerReceiveEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index.json.
        /// </summary>
        internal static string ServerStatusEndpoint {
            get {
                return ResourceManager.GetString("ServerStatusEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will be available in {0}.
        /// </summary>
        internal static string WillBeAvailableIn {
            get {
                return ResourceManager.GetString("WillBeAvailableIn", resourceCulture);
            }
        }
    }
}
